### ISSUE TITLE
Error getting subtitles: Invalid attempt to destructure non-iterable instance

### ISSUE THREAD

**Issue by codekiln** [briansunter/logseq-get-youtube-captions#13]
## Reproduction criteria
1. Open Logseq
2. Create a new page
3. Enter this `{{video https://www.youtube.com/watch?v=2QV3RAOmZ2k}}` and then type `/get-youtube-captions`

## Expected Result
Captions load

## Actual Result
 
<img width="414" alt="image" src="https://github.com/briansunter/logseq-get-youtube-captions/assets/140930/57e3a573-7570-4dea-8cb6-86aea5b33277">

## Provenance
Logseq Version 0.9.18 (71)
Plugins: 
1. Get YouTube Captions v1.2.0
2. Helium v2.1.3 (note: helium was not activated for the block)

**Comment by javierfuentesm** [comment]
Im getting the same error 
<img width="403" alt="image" src="https://github.com/briansunter/logseq-get-youtube-captions/assets/19244527/03122cec-770f-4a13-8701-c9f1c301e695">

**Comment by larrythelopher** [comment]
+1

Would be massively grateful if it got fixed

**Comment by chrisandrewsedu** [comment]
Same here.

**Comment by Autofixer123** [comment]
Hi Brian,
Thank you for awesome plugin.
Having same problem "destructure non-iterable instance" where CC english is available.

**Comment by briansunter** [comment]
Hey! Thanks for reporting this. I just looked into it and I'm seeing the same issue, so I can confirm it's not working anymore on any video I tried.

It seems like something changed on YouTube's side. The library I was using to get the captions is no longer working.

I added a comment on the library, since it seems like others are seeing issues as well

https://github.com/algolia/youtube-captions-scraper/issues/20

Ideally the library authors will fix it, and I'll just use the fixed version. If they don't respond, I'll investigate a different solution than that library for getting the captions, but it may be some time before I can do that.

I believe it's possible to get the captions with a plain HTTP request, rather than the library.

 If someone wanted to look into an alternative method for fetching the captions, it would be greatly appreciated!

**Comment by briansunter** [comment]
Hey Everyone

**Comment by leleitu** [comment]
Thanks Brian, i just need something simple straight forward as the other library, paste the link and display the entire captions. Any recommendations? i am on level 1 learning.

**Comment by codekiln** [comment]
> Please try upgrading to the latest version and let me know if that fixes the problem.
Thanks @briansunter - this is working again; nice work.

**Comment by briansunter** [comment]
Hey @leleitu the captions plugin should be working the same way as before now so you shouldn't need to do anything differently

**Comment by leleitu** [comment]
i spent my saturday trying to fix it..  thanks brian .. you are very helpful

**Comment by Autofixer123** [comment]
BIG Thank You!! Brian
works great again 
👍 :thumbsup:
